openapi: 3.0.0
info:
  title: API Specification
  version: '1.0.0'
servers:
  - url: 'http://localhost:5000'
paths:
  '/':
    get:
      summary: Return greeting message
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'hello world'
    post:
      summary: Receive and return submitted data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '201':
          description: Data received
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
  '/square/{num}':
    get:
      summary: Return the square of the specified number
      parameters:
        - in: path
          name: num
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  square:
                    type: integer