openapi: 3.0.0
info:
  title: Weather Forecast API
  version: '1.0.0'
servers:
  - url: 'http://localhost:5000'
paths:
  /WeatherForecast:
    get:
      summary: Get weather forecast
      operationId: GetWeatherForecast
      responses:
        '200':
          description: Successfully retrieved weather forecast
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
components:
  schemas:
    WeatherForecast:
      type: object
      properties:
        date:
          type: string
          format: date
          description: Date of the forecast
        temperatureC:
          type: integer
          description: Temperature in Celsius
        summary:
          type: string
          description: Weather summary
      required:
        - date
        - temperatureC
        - summary