name: evaluation
on:
  workflow_dispatch:
    

jobs:
  evaluation:
    runs-on: windows-latest
    environment: eng
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install the project dependencies
        run: pip install -r requirements.txt
      
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: download api spec files
        env:
          AZURE_STORAGE_ACCOUNT_URL: ${{ secrets.AZURE_STORAGE_ACCOUNT_URL }}
          AZURE_STORAGE_CONTAINER_NAME: ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}
        run: |
          python prompteval/downloadSpecFiles.py

      - name: setup output
        working-directory: .
        run: |
          mkdir -p results
          touch results/output.jsonl

      - name: generate yml
        env:
          AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
          AZURE_OPENAI_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_DEPLOYMENT }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          RBAC: ${{ secrets.RBAC }}
        run: |
          python prompteval/prompteval.py

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install spectral
        run: npm install -g @stoplight/spectral-cli

      # - name: run spectral
      #   run: |
      #     spectral lint results/cstest_response.yml --ruleset=https://raw.githubusercontent.com/Azure/APICenter-Analyzer/preview/resources/rulesets/oas.yaml --format json -o results/cstest_response_output.json
      #     spectral lint results/pytest_response.yml --ruleset=https://raw.githubusercontent.com/Azure/APICenter-Analyzer/preview/resources/rulesets/oas.yaml --format json -o results/pytest_response_output.json
      #     spectral lint results/pet_response.yml --ruleset=https://raw.githubusercontent.com/Azure/APICenter-Analyzer/preview/resources/rulesets/oas.yaml --format json -o results/pet_response_output.json

      - name: run evaluate
        run: |
          python prompteval/analyse.py

      - uses: actions/upload-artifact@v4
        with:
          name: results
          path: |
            results/